app:./main.cpp ./http_conn/sources/http_conn.cpp ./http_conn/sources/tool.cpp ./thread_pools/sources/sem.cpp ./thread_pools/sources/locker.cpp 
	g++ -o app ./main.cpp ./http_conn/sources/http_conn.cpp ./http_conn/sources/tool.cpp ./thread_pools/sources/sem.cpp ./thread_pools/sources/locker.cpp 
